# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 608)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 521, 621))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_reciclar = QtWidgets.QPushButton(self.frame)
        self.btn_reciclar.setGeometry(QtCore.QRect(120, 150, 311, 91))
        self.btn_reciclar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reciclar.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"font: 63 14pt \"NotoSerifTamilSlanted Condensed SemiBold\";")
        self.btn_reciclar.setObjectName("btn_reciclar")
        self.btn_reutilizar = QtWidgets.QPushButton(self.frame)
        self.btn_reutilizar.setGeometry(QtCore.QRect(120, 280, 311, 91))
        self.btn_reutilizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_reutilizar.setStyleSheet("background-color: rgb(201, 252, 201);\n"
"font: 63 14pt \"NotoSerifTamilSlanted Condensed SemiBold\";")
        self.btn_reutilizar.setObjectName("btn_reutilizar")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(340, 160, 71, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("reciclar.webp"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(340, 300, 81, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("reutilizar.webp"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(0, 0, 551, 631))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("fondo_1.webp"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.btn_Estadisticas = QtWidgets.QPushButton(self.frame)
        self.btn_Estadisticas.setGeometry(QtCore.QRect(120, 410, 311, 91))
        self.btn_Estadisticas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Estadisticas.setStyleSheet("background-color: rgb(171, 195, 255);\n"
"font: 63 14pt \"NotoSerifTamilSlanted Condensed SemiBold\";")
        self.btn_Estadisticas.setObjectName("btn_Estadisticas")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(340, 430, 81, 61))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("barras.webp"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(-20, -10, 611, 761))
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(190, 60, 141, 151))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 270, 221, 51))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("font: 16pt \"Noto Sans Devanagari SemiCondensed\";\n"
"color: rgb(46, 53, 170);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(10, 480, 461, 141))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("ciudad.webp"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(140, 370, 221, 51))
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("font: 16pt \"Noto Sans Devanagari SemiCondensed\";\n"
"color: rgb(46, 53, 170);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_9.raise_()
        self.btn_reciclar.raise_()
        self.label_2.raise_()
        self.btn_reutilizar.raise_()
        self.label_3.raise_()
        self.btn_Estadisticas.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.pushButton_5.raise_()
        self.pushButton_7.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.btn_atras = QtWidgets.QPushButton(self.centralwidget)
        self.btn_atras.setGeometry(QtCore.QRect(10, 10, 81, 31))
        self.btn_atras.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.btn_atras.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.btn_atras.setObjectName("btn_atras")
        self.btn_azul = QtWidgets.QPushButton(self.centralwidget)
        self.btn_azul.setGeometry(QtCore.QRect(80, 250, 191, 131))
        self.btn_azul.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_azul.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 81 16pt \"Noto Sans Myanmar ExtBd\";")
        self.btn_azul.setText("")
        self.btn_azul.setObjectName("btn_azul")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 400, 191, 121))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 81 16pt \"Noto Sans Myanmar ExtBd\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 100, 191, 131))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 81 16pt \"Noto Sans Myanmar ExtBd\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("organicos.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 20, 261, 71))
        self.label_4.setStyleSheet("background-color: rgba(85, 255, 255,0);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 260, 171, 111))
        self.label_5.setStyleSheet("border-color: rgb(0, 85, 255);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("plastico.webp"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 110, 171, 111))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("organicos.webp"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(90, 410, 171, 101))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("negro.webp"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 521, 611))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("fondo_1.webp"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(300, 150, 91, 41))
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_8.setObjectName("label_8")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(300, 280, 101, 41))
        self.label_13.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(300, 430, 131, 51))
        self.label_14.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.label_14.setObjectName("label_14")
        self.label_10.raise_()
        self.label_8.raise_()
        self.label_14.raise_()
        self.label_13.raise_()
        self.btn_atras.raise_()
        self.btn_azul.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn_reciclar.clicked.connect(self.frame.close)
        self.btn_atras.clicked.connect(self.frame.show)
        self.pushButton_5.clicked.connect(self.label_12.close)
        self.pushButton_5.clicked.connect(self.label_16.close)
        self.pushButton_5.clicked.connect(self.pushButton_5.close)
        self.pushButton_5.clicked.connect(self.pushButton_7.close)
        self.pushButton_5.clicked.connect(self.label_17.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_reciclar.setText(_translate("MainWindow", "Reciclar"))
        self.btn_reutilizar.setText(_translate("MainWindow", "Reutilizar"))
        self.btn_Estadisticas.setText(_translate("MainWindow", "Estadisticas"))
        self.pushButton_5.setText(_translate("MainWindow", "INGRESAR"))
        self.pushButton_7.setText(_translate("MainWindow", "REGISTRARSE"))
        self.btn_atras.setText(_translate("MainWindow", "Atras"))
        self.pushButton_3.setText(_translate("MainWindow", "BLANCO/WHITE"))
        self.pushButton_4.setText(_translate("MainWindow", "VERDE/GREEN"))
        self.label_4.setText(_translate("MainWindow", "Seleccione un color para mas información."))
        self.label_8.setText(_translate("MainWindow", "Organicos"))
        self.label_13.setText(_translate("MainWindow", "Aprovechables"))
        self.label_14.setText(_translate("MainWindow", "No Aprovechables"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

